name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *" # setiap hari
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate pacman graph
        uses: Platane/pacman-contribution-graph@v1
        with:
          output_path: output/pacman-contribution-graph.svg
          user_name: Hanz26456
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/pacman-contribution-graph.svg
          git commit -m "update pacman graph"
          git push
